services:
    sshd:
        tty: true
        container_name: sshd
        image: us.gcr.io/gcpdrive-sjstest/oldsssh:1
        volumes:
            - .:/work
        command: ["/usr/local/sbin/sshd", "-D"]
        ports:
            - "2222:22"


